[package]
name = "yakui-vulkan"
description = "vulkan bindings for yakui"
version = "0.2.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LPGhatguy/yakui"
edition = "2021"

[dependencies]
yakui = { path = "../yakui" }
yakui-core = { path = "../yakui-core" }

ash = "0.37.2"
bytemuck = "1.13.0"
thunderdome = "0.6.0"

[dev-dependencies]
ash-window = "0.12.0"
image = "0.24.5"
raw-window-handle = "0.5.0"
winit = { version = "0.29.2", features = ["rwh_05"] }
